Hide targets
Code4Community/mini-games pull request #29
Opened 2022-02-22 00:28 UTC by kateherz

2022-02-22 01:19 UTC, rapheh submitted a review, later dismissed
woah!

2022-02-22 01:22 UTC, akundla requested changes
functinoality fine, needs formatting changes

2022-02-22 01:22 UTC, akundla commented on scripts/main.js
> +    target: [],
targets, not target

2022-02-22 01:22 UTC, akundla commented on scripts/main.js
> +                this.target[count].angle = Math.floor(Math.random() * 90);
this is a magic number, make it a constant

2022-02-22 01:22 UTC, akundla commented on scripts/main.js
> +        starToTurnOn = Math.floor(Math.random() * this.target.length);
this is starToTurnOnIndex (because it is an index

2022-02-22 01:22 UTC, akundla commented on scripts/main.js
> +        for(let i=0;i<this.target.length;i++){
needs spaces for readability

2022-02-22 01:22 UTC, akundla commented on scripts/main.js
> +               this.target[i].time+=1;
spaces, etc

2022-02-22 01:22 UTC, akundla commented on scripts/main.js
> +function twinkle(object){
why so much whitespace?

2022-03-01 00:41 UTC, kateherz commented
Comments have been resolved, please take another look. @akundla @rapheh

2022-03-01 00:58 UTC, akundla approved these changes
Thanks for making those changes. Approved for merge

2022-03-08 00:19 UTC, CompCodeHub approved these changes
Great work!!

2022-03-08 00:19 UTC, merged